<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Sonic Time Travelers: Can a Song’s Lyrics Place It in Its Era? – Sonic Time Travelers</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-a13d9807c4567286ce7a414117ac4c47.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Sonic Time Travelers</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./visualizations.html"> 
<span class="menu-text">Visualizations</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./era-classifier.html"> 
<span class="menu-text">Model Implementation</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./results.html" aria-current="page"> 
<span class="menu-text">Results Summary</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./results.pdf" target="_blank"> 
<span class="menu-text">📄 Download Report</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/phuonganhdangamy/jsc370-project"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#i.-introduction" id="toc-i.-introduction" class="nav-link active" data-scroll-target="#i.-introduction">I. Introduction</a>
  <ul class="collapse">
  <li><a href="#research-question" id="toc-research-question" class="nav-link" data-scroll-target="#research-question">Research Question</a></li>
  <li><a href="#hypotheses" id="toc-hypotheses" class="nav-link" data-scroll-target="#hypotheses">Hypotheses</a></li>
  <li><a href="#novelty" id="toc-novelty" class="nav-link" data-scroll-target="#novelty">Novelty</a></li>
  </ul></li>
  <li><a href="#ii.-methods" id="toc-ii.-methods" class="nav-link" data-scroll-target="#ii.-methods">II. Methods</a>
  <ul class="collapse">
  <li><a href="#data-sources-and-acquisition" id="toc-data-sources-and-acquisition" class="nav-link" data-scroll-target="#data-sources-and-acquisition">Data Sources and Acquisition</a></li>
  <li><a href="#data-cleaning-and-labeling" id="toc-data-cleaning-and-labeling" class="nav-link" data-scroll-target="#data-cleaning-and-labeling">Data Cleaning and Labeling</a></li>
  <li><a href="#feature-engineering" id="toc-feature-engineering" class="nav-link" data-scroll-target="#feature-engineering">Feature Engineering</a></li>
  <li><a href="#models-and-training" id="toc-models-and-training" class="nav-link" data-scroll-target="#models-and-training">Models and Training</a></li>
  </ul></li>
  <li><a href="#iii.-results" id="toc-iii.-results" class="nav-link" data-scroll-target="#iii.-results">III. Results</a>
  <ul class="collapse">
  <li><a href="#model-selection" id="toc-model-selection" class="nav-link" data-scroll-target="#model-selection">Model Selection</a></li>
  <li><a href="#final-model-performance" id="toc-final-model-performance" class="nav-link" data-scroll-target="#final-model-performance">Final Model Performance</a></li>
  <li><a href="#confusion-patterns" id="toc-confusion-patterns" class="nav-link" data-scroll-target="#confusion-patterns">Confusion Patterns</a></li>
  <li><a href="#feature-importance" id="toc-feature-importance" class="nav-link" data-scroll-target="#feature-importance">Feature Importance</a></li>
  <li><a href="#the-nostalgia-sells-hypothesis" id="toc-the-nostalgia-sells-hypothesis" class="nav-link" data-scroll-target="#the-nostalgia-sells-hypothesis">The Nostalgia Sells Hypothesis</a></li>
  </ul></li>
  <li><a href="#iv.-conclusions-and-summary" id="toc-iv.-conclusions-and-summary" class="nav-link" data-scroll-target="#iv.-conclusions-and-summary">IV. Conclusions and Summary</a>
  <ul class="collapse">
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#key-findings" id="toc-key-findings" class="nav-link" data-scroll-target="#key-findings">Key Findings</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">Limitations</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="results.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Sonic Time Travelers: Can a Song’s Lyrics Place It in Its Era?</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="i.-introduction" class="level2">
<h2 class="anchored" data-anchor-id="i.-introduction">I. Introduction</h2>
<p>Music, like fashion, appears to move in cycles. Some contemporary artists are frequently noted for their retro aesthetics despite releasing new material, and the marketing concept of “nostalgia sells” (promoting products that evoke emotional familiarity to drive consumer decisions) has become increasingly prominent in the music industry. This raises a natural question: is lyrical nostalgia statistically measurable, and does it correlate with commercial success?</p>
<p>This project approaches that question through the lens of computational text analysis. By treating song lyrics as the primary data source, we ask whether the words a song uses are enough to reliably identify the decade it came from, and whether modern songs that “sound old” lyrically actually attract more listener engagement.</p>
<section id="research-question" class="level3">
<h3 class="anchored" data-anchor-id="research-question">Research Question</h3>
<blockquote class="blockquote">
<p><em>Can a song’s lyrical identity reliably place it in its era, and do modern songs whose lyrics read as vintage actually perform better commercially?</em></p>
</blockquote>
</section>
<section id="hypotheses" class="level3">
<h3 class="anchored" data-anchor-id="hypotheses">Hypotheses</h3>
<p><strong>Primary Hypothesis:</strong> Lyrical embeddings carry meaningful decade signal and a classifier trained on them will perform above chance. However, adjacent decades, particularly the 1990s–2000s and 2010s–2020s transitions will be systematically confused due to shared vocabulary and gradual thematic evolution.</p>
<p><strong>Secondary Hypothesis:</strong> Modern songs from the 2010s and 2020s that are misclassified as belonging to the 1980s or 1990s will attract more listener engagement than correctly classified modern songs, supporting a “nostalgia sells” theory.</p>
</section>
<section id="novelty" class="level3">
<h3 class="anchored" data-anchor-id="novelty">Novelty</h3>
<p>Most existing work using music data relies on static Kaggle datasets and focuses on audio features alone, ignoring the lyrical dimension entirely. This project is distinctive in several ways. All data is collected live through API calls rather than downloaded as a pre-assembled dataset, giving full control over sampling strategy and decade balance. Multiple data sources such as Spotify, Genius, andMusicBrainz are integrated into a unified analysis pipeline. Finally, the secondary hypothesis directly operationalizes the nostalgia sells concept using listener engagement as a measurable outcome.</p>
<hr>
</section>
</section>
<section id="ii.-methods" class="level2">
<h2 class="anchored" data-anchor-id="ii.-methods">II. Methods</h2>
<section id="data-sources-and-acquisition" class="level3">
<h3 class="anchored" data-anchor-id="data-sources-and-acquisition">Data Sources and Acquisition</h3>
<p>Data collection draws from three external sources, each serving a distinct role in the analysis.</p>
<p><strong>Spotify Web API</strong> provides track metadata and decade labeling. Tracks are retrieved using decade-specific search queries combining release year ranges with genre keywords (e.g., <code>rock year:1980-1989</code>). To ensure genre diversity within each decade, four genre branches are sampled per era: Rock, Pop, and Hip Hop are included consistently across all five decades given their sustained cultural presence, while decade-specific genres like Dance (1980s), RnB (1990s), Country (2000s), EDM (2010s), and Latin (2020s) capture the unique sonic flavors of each era. Due to Spotify’s API rate limits under development mode, collection was spread across multiple days in batches of up to 1,000 tracks per query.</p>
<p><strong>Genius API and web scraping</strong> provide raw song lyrics. For each track, the Genius search API is queried with the cleaned artist name and track title to retrieve the lyrics page URL, after which BeautifulSoup scrapes the page content. Track names are pre-cleaned by stripping parenthetical annotations such as “(Remastered)” or “(feat. Artist)” to improve search accuracy. Lyrics are cleaned by removing section headers (e.g., <code>[Verse 1]</code>), non-ASCII characters, and excess whitespace. Songs returning fewer than 20 words after cleaning are treated as failed scrapes. Genius page view counts are also fetched for each successfully scraped song as a proxy for listener engagement. A checkpoint is saved every 500 tracks to make the pipeline fully resumable.</p>
<p><strong>MusicBrainz API</strong> supplements Spotify metadata with cultural context, including each artist’s country and city of origin and community-contributed genre tags. Artist records are retrieved by name search, then enriched with a detailed tag fetch. MusicBrainz enforces a strict rate limit of one request per second, which is respected via a fixed 1.1-second sleep between calls. A match confidence score is retained for each result to filter low-quality matches.</p>
</section>
<section id="data-cleaning-and-labeling" class="level3">
<h3 class="anchored" data-anchor-id="data-cleaning-and-labeling">Data Cleaning and Labeling</h3>
<p>All raw data sources are cleaned and aligned in a single consolidated step after collection is complete. Release years are extracted from Spotify’s release date field and records outside the 1980-2026 range are removed. Tracks identified as remasters, live versions, remixes, or deluxe editions via regex are filtered out. Deduplication retains only the earliest known release per artist and track name pair to preserve each song’s true era of origin. Decade labels are then assigned by binning release years into five categories (1980s through 2020s). A stratified cap of 2,000 songs per decade is applied to correct for overrepresentation of certain eras in the raw data.</p>
<p>Lyrics, embeddings, MusicBrainz enrichment, and pageview counts are merged against the cleaned Spotify track list using track ID and artist ID. Tracks that failed MusicBrainz matching are retained with null fields rather than dropped, since artist origin is a supplementary rather than required feature. The final master dataset retains only tracks for which lyrical embeddings were successfully generated.</p>
<div id="tbl-cleaning" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cleaning-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Data cleaning pipeline
</figcaption>
<div aria-describedby="tbl-cleaning-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Stage</th>
<th>N Tracks</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Raw collected</td>
<td>15,147</td>
</tr>
<tr class="even">
<td>After remaster/live filter</td>
<td>13,721</td>
</tr>
<tr class="odd">
<td>After deduplication</td>
<td>12,983</td>
</tr>
<tr class="even">
<td>After stratified cap</td>
<td>9,854</td>
</tr>
<tr class="odd">
<td>Master dataset (with embeddings)</td>
<td>9,176</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-decades" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-decades-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Decade distribution before and after stratified cap
</figcaption>
<div aria-describedby="tbl-decades-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Decade</th>
<th>Before Cap</th>
<th>After Cap</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1980s</td>
<td>2,542</td>
<td>2,000</td>
</tr>
<tr class="even">
<td>1990s</td>
<td>3,137</td>
<td>2,000</td>
</tr>
<tr class="odd">
<td>2000s</td>
<td>3,064</td>
<td>2,000</td>
</tr>
<tr class="even">
<td>2010s</td>
<td>1,854</td>
<td>1,854</td>
</tr>
<tr class="odd">
<td>2020s</td>
<td>2,386</td>
<td>2,000</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The 2010s are the only decade that did not reach the 2,000-track cap, retaining all 1,854 collected tracks. Embedding coverage, the share of the cleaned audio dataset for which lyrics were successfully scraped and embedded, is 93.1%.</p>
</section>
<section id="feature-engineering" class="level3">
<h3 class="anchored" data-anchor-id="feature-engineering">Feature Engineering</h3>
<p>Each song is represented as a 389-dimensional feature vector combining a 384-dimensional semantic embedding with five engineered features.</p>
<p><strong>Lyrical embeddings</strong> are generated using the <code>all-MiniLM-L6-v2</code> sentence transformer model, which maps each song’s full lyric text to a fixed-length dense vector capturing semantic meaning. This allows the model to compare songs in a continuous embedding space regardless of surface vocabulary differences.</p>
<p><strong>Sentiment</strong> is computed using the VADER lexicon, producing a compound polarity score ranging from -1 (most negative) to +1 (most positive). VADER is well-suited for song lyrics as it was designed for informal expressive text and is sensitive to capitalization, punctuation, and intensifiers.</p>
<p><strong>Rhyme density</strong> measures the proportion of line endings that share a phonetic rhyme sound with at least one other line in the song. Rhyme signatures are derived using the CMU Pronouncing Dictionary via the <code>pronouncing</code> library, where the last two phonemes of each line-ending word serve as the rhyme fingerprint.</p>
<p><strong>Repetition ratio</strong> captures the proportion of lyric lines that are exact duplicates of another line within the same song, designed to quantify hook-driven or chorus-heavy song structures that became dominant in the streaming era.</p>
<p><strong>Language</strong> is detected using the <code>langdetect</code> library and binarized into an <code>is_english</code> flag. This is included because non-English songs which are disproportionately represented in the 2020s due to Latin music sampling may be encoded differently by an English-dominant embedding model, and the flag allows the classifier to treat language as an explicit rather than latent signal.</p>
</section>
<section id="models-and-training" class="level3">
<h3 class="anchored" data-anchor-id="models-and-training">Models and Training</h3>
<p>The classification task predicts the decade label (five classes: 1980s through 2020s) from the 389-dimensional feature vector. The dataset is split 70/15/15 into training, validation, and test sets using an <strong>artist-stratified</strong> assignment strategy: all songs by a given artist are assigned to the same split, preventing the model from exploiting artist-specific stylistic signatures rather than genuine era characteristics.</p>
<p>Six model configurations are evaluated across three model families and two feature spaces:</p>
<ul>
<li><strong>Logistic Regression</strong> serves as the interpretable baseline, trained in multinomial mode with L2 regularization.</li>
<li><strong>XGBoost</strong> is a gradient-boosted tree ensemble expected to capture non-linear interactions in the embedding space. Hyperparameters are selected via 5-fold cross-validated grid search over the training set, searching across number of estimators (200, 400, 600), max depth (3, 4, 6), learning rate (0.05, 0.1), and min child weight (1, 3). Accuracy is used as the grid search scoring metric given the balanced class distribution.</li>
<li><strong>Random Forest</strong> is a bagged tree ensemble trained with the best hyperparameters found by a separate grid search over number of estimators, max depth, max features, and min samples split.</li>
</ul>
<p>Each model family is trained in two configurations: on <strong>PCA-reduced features</strong> (retaining 95% of variance, yielding 229 principal components) and on the <strong>full 389-dimensional scaled feature space</strong>. A single <code>StandardScaler</code> is fit on the training set only to prevent data leakage.</p>
<p>Model selection is based on <strong>macro-averaged F1 score</strong> on the validation set, chosen as the primary metric because it treats all five decade classes equally regardless of support size. The best-performing model on validation is then evaluated once on the held-out test set to produce final reported performance figures.</p>
<hr>
</section>
</section>
<section id="iii.-results" class="level2">
<h2 class="anchored" data-anchor-id="iii.-results">III. Results</h2>
<section id="model-selection" class="level3">
<h3 class="anchored" data-anchor-id="model-selection">Model Selection</h3>
<p>Six configurations are compared on the validation set to select the final model. <a href="#tbl-comparison" class="quarto-xref">Table&nbsp;3</a> summarizes the metrics for all configurations.</p>
<div class="cell" data-execution_count="2">
<div id="tbl-comparison" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="2">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Results on the validation set for all model configurations.
</figcaption>
<div aria-describedby="tbl-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Model</th>
<th data-quarto-table-cell-role="th">Val F1 (macro)</th>
<th data-quarto-table-cell-role="th">Accuracy</th>
<th data-quarto-table-cell-role="th">Precision (macro)</th>
<th data-quarto-table-cell-role="th">Recall (macro)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Logistic Regression (PCA)</td>
<td>0.448</td>
<td>0.458</td>
<td>0.446</td>
<td>0.452</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Logistic Regression (Full)</td>
<td>0.449</td>
<td>0.457</td>
<td>0.448</td>
<td>0.452</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>XGBoost (PCA)</td>
<td>0.432</td>
<td>0.444</td>
<td>0.431</td>
<td>0.438</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>XGBoost (Full)</td>
<td>0.478</td>
<td>0.485</td>
<td>0.477</td>
<td>0.481</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>Random Forest (PCA)</td>
<td>0.405</td>
<td>0.425</td>
<td>0.409</td>
<td>0.419</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>Random Forest (Full)</td>
<td>0.437</td>
<td>0.454</td>
<td>0.440</td>
<td>0.448</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p>All models substantially outperform the random-chance baseline of 0.20. XGBoost trained on the full 389-dimensional feature space achieves the highest validation F1, consistent with gradient-boosted trees’ ability to perform implicit feature selection. Logistic regression performs competitively despite its simplicity, suggesting that a meaningful share of decade information is encoded in linearly separable directions within the embedding space. Based on these results, <strong>XGBoost (Full)</strong> is selected as the final model for test set evaluation and interpretation.</p>
</section>
<section id="final-model-performance" class="level3">
<h3 class="anchored" data-anchor-id="final-model-performance">Final Model Performance</h3>
<p>The selected model is evaluated once on the held-out test set. <a href="#tbl-test-report" class="quarto-xref">Table&nbsp;4</a> shows per-class precision, recall, and F1, and <a href="#fig-f1-bar" class="quarto-xref">Figure&nbsp;1</a> visualizes the per-class F1 scores.</p>
<div class="cell" data-execution_count="3">
<div id="tbl-test-report" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="3">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-test-report-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Per-class precision, recall, and F1 for XGBoost (Full) on the held-out test set.
</figcaption>
<div aria-describedby="tbl-test-report-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Precision</th>
<th data-quarto-table-cell-role="th">Recall</th>
<th data-quarto-table-cell-role="th">F1</th>
<th data-quarto-table-cell-role="th">Support</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Decade</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">1980s</th>
<td>0.633</td>
<td>0.494</td>
<td>0.555</td>
<td>314</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1990s</th>
<td>0.452</td>
<td>0.491</td>
<td>0.470</td>
<td>267</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2000s</th>
<td>0.451</td>
<td>0.451</td>
<td>0.451</td>
<td>275</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2010s</th>
<td>0.444</td>
<td>0.470</td>
<td>0.456</td>
<td>234</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2020s</th>
<td>0.730</td>
<td>0.789</td>
<td>0.758</td>
<td>402</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">macro avg</th>
<td>0.542</td>
<td>0.539</td>
<td>0.538</td>
<td>1492</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">weighted avg</th>
<td>0.563</td>
<td>0.561</td>
<td>0.560</td>
<td>1492</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<div id="cell-fig-f1-bar" class="cell" data-fig-format="png" data-execution_count="4">
<div class="cell-output cell-output-display">
<div id="fig-f1-bar" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-f1-bar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="results_files/figure-html/fig-f1-bar-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-f1-bar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Per-class F1 for XGBoost (Full) on the held-out test set.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The 1980s and 2020s are the most reliably classified decades, while the 1990s and 2000s show the lowest F1 scores. This is consistent with the primary hypothesis that adjacent decades share more lyrical vocabulary and are therefore harder to distinguish.</p>
</section>
<section id="confusion-patterns" class="level3">
<h3 class="anchored" data-anchor-id="confusion-patterns">Confusion Patterns</h3>
<p><a href="#fig-cm" class="quarto-xref">Figure&nbsp;2</a> shows the full confusion matrix on the test set.</p>
<div id="cell-fig-cm" class="cell" data-fig-format="png" data-execution_count="5">
<div class="cell-output cell-output-display">
<div id="fig-cm" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="results_files/figure-html/fig-cm-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Confusion matrix for XGBoost (Full) on the held-out test set.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The final test set confusion matrix reveals several striking patterns. The 2020s dominates with 317 correct predictions out of 402 songs (79% recall), by far the highest of any decade. This confirms that contemporary lyrical style is the most distinctive era in the corpus, likely driven by the combination of modern slang, Latin influence, and streaming-optimized song structures. The 1980s follows with 155 correct (49% recall), benefiting from its distinctive rock and dance-era vocabulary. The middle decades are substantially harder: the 2000s achieves only 124 correct (45% recall) and the 2010s only 110 (46% recall), with the 1990s sitting at 131 (52% recall).</p>
<p>The off-diagonal tells an equally interesting story. The 1990s bleeds heavily into the 2020s (30 songs predicted as 2020s), which is unexpected for non-adjacent decades and may reflect the growing trend of 90s revival aesthetics in modern music. The 2000s similarly leaks into the 2020s (42 songs), suggesting that some early-2000s lyrical styles have more in common with contemporary music than with the 1990s. The 1980s–1990s boundary remains the most classically confused adjacent pair (73 songs from the 1980s predicted as 1990s), consistent with the gradual transition from classic rock to grunge and early hip hop. Notably, almost no songs from any decade are predicted as 1980s except true 1980s tracks, meaning the model treats the 1980s as a fairly exclusive category that is hard to fake.</p>
</section>
<section id="feature-importance" class="level3">
<h3 class="anchored" data-anchor-id="feature-importance">Feature Importance</h3>
<p>To understand which features most drive decade classification, SHAP values are computed on the XGBoost (Full) model over a sample of 500 test-set tracks. <a href="#fig-shap" class="quarto-xref">Figure&nbsp;3</a> shows the top 20 features by mean absolute SHAP value.</p>
<div id="cell-fig-shap" class="cell" data-fig-format="png" data-execution_count="6">
<div class="cell-output cell-output-display">
<div id="fig-shap" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-shap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="results_files/figure-html/fig-shap-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-shap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Top 20 features by mean absolute SHAP value for XGBoost (Full). Engineered features are shown in orange; embedding dimensions in blue.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Engineered features such as <code>repetition_ratio</code>, <code>lyric_word_count</code>, and <code>rhyme_density</code> rank among the top 20 overall features, appearing well above the majority of individual embedding dimensions. This confirms that the model leverages these interpretable structural properties rather than relying solely on semantic embedding coordinates. A notable pattern is the spike in <code>repetition_ratio</code> for the 2010s, consistent with the dominance of hook-driven, streaming-optimized song structures in that era.</p>
</section>
<section id="the-nostalgia-sells-hypothesis" class="level3">
<h3 class="anchored" data-anchor-id="the-nostalgia-sells-hypothesis">The Nostalgia Sells Hypothesis</h3>
<p>We define <em>time travelers</em> as songs released in the 2010s or 2020s that the model predicts as belonging to the 1980s or 1990s — songs whose lyrical identity reads as vintage despite their contemporary release date. Among the <strong>1492</strong> test-set songs, <strong>63</strong> (4.2%) are classified as time travelers. Interactive examples are available in the UMAP visualization on the <a href="./visualizations.html">Explore Data</a> page.</p>
<p>To test the secondary hypothesis, we compare Genius pageview counts between time travelers and correctly classified modern songs across the full dataset of 2010s/2020s tracks with available pageview data.</p>
<div id="cell-nostalgia-plot-log" class="cell" data-fig-format="png" data-execution_count="8">
<div class="cell-output cell-output-display">
<div id="nostalgia-plot-log" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="results_files/figure-html/nostalgia-plot-log-output-1.png" class="img-fluid figure-img"></p>
<figcaption>Genius pageview distributions for modern songs (2010s/2020s) split by whether the model predicts them as vintage (1980s/1990s). Displayed in log scale to accommodate the wide range of pageviews.</figcaption>
</figure>
</div>
</div>
</div>
<div id="cell-nostalgia-plot" class="cell" data-fig-format="png" data-execution_count="9">
<div class="cell-output cell-output-display">
<div id="nostalgia-plot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="results_files/figure-html/nostalgia-plot-output-1.png" class="img-fluid figure-img"></p>
<figcaption>Genius pageview distributions for modern songs (2010s/2020s) split by whether the model predicts them as vintage (1980s/1990s).</figcaption>
</figure>
</div>
</div>
</div>
<p>The pageview distributions provide no support for the nostalgia sells hypothesis.</p>
<p>On the log scale, correctly classified modern songs have a visibly higher median (approximately 10^5, or 90,000 pageviews) compared to time travelers (approximately 10^4.8, or 65,000 pageviews), and the correctly classified group extends further into the upper tail, reaching past 10^7 while time travelers cap around 10^6.5.</p>
<p>The raw scale plot makes the extreme skew even more apparent: the correctly classified group contains songs with upwards of 17 million Genius pageviews while time travelers max out around 4 million. The vast majority of songs in both groups cluster near zero regardless of scale, confirming that a small number of viral outliers dominate the mean. Even on the median, time travelers do not outperform correctly classified songs. If a nostalgia sells effect exists in popular music, it is not detectable through Genius pageviews in this corpus, and the evidence leans in the opposite direction: the highest-engagement modern songs tend to be those that sound distinctly contemporary rather than vintage.</p>
<p>It is worth noting that Genius pageviews are a narrow proxy for commercial success. Listener engagement in the modern era is more naturally measured through streaming platform play counts, YouTube views, TikTok usage, or social media virality. A song can accumulate enormous streaming numbers without ever driving significant lyric-lookup traffic on Genius, and conversely, a lyrically complex or nostalgic song may attract disproportionate Genius visits precisely because listeners want to parse its words rather than because it is commercially dominant. Hence, the absence of a nostalgia effect in this analysis should therefore be interpreted cautiously.</p>
<hr>
</section>
</section>
<section id="iv.-conclusions-and-summary" class="level2">
<h2 class="anchored" data-anchor-id="iv.-conclusions-and-summary">IV. Conclusions and Summary</h2>
<section id="summary" class="level3">
<h3 class="anchored" data-anchor-id="summary">Summary</h3>
<p>This project investigated whether song lyrics carry sufficient temporal signal to reliably identify a song’s decade of origin, and whether modern songs with vintage lyrical identities attract more listener engagement.</p>
<p>On the first question, the answer is yes, but imperfectly. XGBoost trained on full lyrical embeddings augmented with engineered features achieves a macro-averaged F1 of 0.538 on the held-out test set, substantially above the 0.20 random-chance baseline. This confirms that lyrical language encodes meaningful temporal signal. However, classification degrades specifically at adjacent-decade boundaries, particularly the 1990s–2000s transition, supporting the hypothesis that lyrical evolution is gradual rather than discrete.</p>
<p>On the second question, the pageview analysis does not find significant evidence that time travelers attract greater engagement, leaving open the nostalgia sells theory in the lyrical domain.</p>
</section>
<section id="key-findings" class="level3">
<h3 class="anchored" data-anchor-id="key-findings">Key Findings</h3>
<ul>
<li><p><strong>Decade signal is real but subtle.</strong> Lyrical embeddings outperform chance by a wide margin, but overall accuracy remains moderate, indicating that lyrics are a noisy but informative temporal cue.</p></li>
<li><p><strong>Adjacent decades are the hardest to distinguish.</strong> The 1990s-2000s transition is the most confusing boundary. The 1980s and 2020s are the most distinctive, likely due to their particularly characteristic vocabularies (i.e., rock and dance-era terminology in the 1980s and contemporary slang and Latin influence in the 2020s).</p></li>
<li><p><strong>XGBoost is the best model.</strong> The full-embedding XGBoost matches or outperforms the PCA-reduced variant, consistent with gradient-boosted trees’ ability to perform implicit feature selection without explicit dimensionality reduction.</p></li>
<li><p><strong>Engineered features add value.</strong> Rhyme density and repetition ratio rank among the top overall SHAP features, confirming that structural lyrical properties carry complementary decade signal beyond what the dense semantic embedding alone captures.</p></li>
</ul>
</section>
<section id="limitations" class="level3">
<h3 class="anchored" data-anchor-id="limitations">Limitations</h3>
<ul>
<li><p><strong>Survivor bias.</strong> Older decades are represented only by tracks visible enough to surface in Spotify search results, likely overrepresenting canonical songs and underestimating lyrical diversity within each era.</p></li>
<li><p><strong>Uneven lyrics coverage.</strong> Genius skews toward contemporary music; the 1980s have a lower lyrics match rate, which may disadvantage the classifier when predicting that decade.</p></li>
<li><p><strong>Genre composition confounds decade.</strong> Genre clusters more strongly than decade in the embedding space. Because genre distributions shift across decades (e.g., EDM in the 2010s, Latin in the 2020s), the classifier may be partially learning genre rather than pure lyrical era identity.</p></li>
<li><p><strong>Language sensitivity.</strong> Spanish-language tracks, most prevalent in the 2020s Latin sampling, may be encoded differently by an English-dominant embedding model. The <code>is_english</code> binary flag partially controls for this but does not fully address it.</p></li>
<li><p><strong>Genius pageviews as engagement proxy.</strong> Pageview counts reflect lyric-lookup behavior more than streaming popularity. Songs that are lyrically interesting or confusing may attract disproportionate Genius traffic regardless of commercial success, introducing noise into the nostalgia sells analysis.</p></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Amy Dang | JSC370 | University of Toronto | 2026</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>